
GET http://localhost:8000/friends

### GET FRIEND
GET http://localhost:8000/friends/prani

### ADD A FRIEND
POST http://localhost:8000/addfriend
Content-Type: application/json

{
    "name": "pran",
    "status": "friend"
}

### UPDATE STATUS OF A FRIEND
PATCH http://localhost:8000/changestatus
Content-Type: application/json

{
    "name": "tom",
    "newStatus": "enemy"
}


###DELETE A FRIEND
DELETE http://localhost:8000/friends
Content-Type: application/json

{
    "name": "banana"
}


